"""Natural-language-inference backend for word grounding."""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from typing import Any

import numpy as np


class NliGroundingBackend:
    """Score word/concept hypotheses with an NLI-fine-tuned encoder."""

    _WORD_RE = re.compile(r"[A-Za-z]+(?:['’][A-Za-z]+)?")

    def __init__(
        self,
        model_id: str,
        device: str = "auto",
        window_stride: int = 128,
    ) -> None:
        self.model_id = model_id
        self.device = device
        self.window_stride = window_stride
        self.tokenizer: Any | None = None
        self.model: Any | None = None
        self.device_: Any | None = None
        self.max_length_: int | None = None
        self.entailment_index_: int | None = None

    def load(self) -> "NliGroundingBackend":
        if self.model is not None:
            return self
        try:
            import torch
            from transformers import AutoModelForSequenceClassification, AutoTokenizer
        except ImportError as exc:
            raise RuntimeError(
                "NLI grounding requires torch and transformers to be installed."
            ) from exc

        self.tokenizer = AutoTokenizer.from_pretrained(self.model_id)
        self.model = AutoModelForSequenceClassification.from_pretrained(self.model_id)
        if self.device == "auto":
            if torch.cuda.is_available():
                selected_device = "cuda"
            elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
                selected_device = "mps"
            else:
                selected_device = "cpu"
        else:
            selected_device = self.device
        self.device_ = torch.device(selected_device)
        self.model.to(self.device_)
        self.model.eval()

        configured_max_length = getattr(self.tokenizer, "model_max_length", 512)
        model_max_length = getattr(self.model.config, "max_position_embeddings", 512)
        if configured_max_length > 100_000:
            configured_max_length = model_max_length
        self.max_length_ = max(2, min(int(configured_max_length), int(model_max_length)))
        labels = getattr(self.model.config, "id2label", {}) or {}
        self.entailment_index_ = next(
            (
                int(index)
                for index, label in labels.items()
                if "entail" in str(label).casefold()
            ),
            None,
        )
        if self.entailment_index_ is None:
            raise ValueError(
                f"NLI model {self.model_id!r} does not expose an entailment label"
            )
        if not 0 <= self.window_stride < self.max_length_ - 1:
            raise ValueError(
                "window_stride must be non-negative and smaller than the NLI context window"
            )
        return self

    def _require_loaded(self) -> tuple[Any, Any, Any, int, int]:
        if self.model is None or self.tokenizer is None or self.device_ is None:
            self.load()
        if (
            self.model is None
            or self.tokenizer is None
            or self.device_ is None
            or self.max_length_ is None
            or self.entailment_index_ is None
        ):
            raise RuntimeError("NLI grounding model is not loaded")
        return (
            self.model,
            self.tokenizer,
            self.device_,
            self.max_length_,
            self.entailment_index_,
        )

    def _premise_windows(self, text: str) -> list[tuple[str, int, int]]:
        _, tokenizer, _, max_length, _ = self._require_loaded()
        encoded = tokenizer(text, add_special_tokens=False, return_offsets_mapping=True)
        input_ids = list(encoded["input_ids"])
        offsets = list(encoded["offset_mapping"])
        if not input_ids:
            return [(text, 0, len(text))]

        # Reserve room for the hypothesis and pair special tokens. The
        # hypotheses generated by TextGraphicalizer are deliberately short.
        premise_budget = max(1, max_length - 64)
        if len(input_ids) <= premise_budget:
            return [(text, 0, len(text))]

        windows: list[tuple[str, int, int]] = []
        step = max(1, premise_budget - self.window_stride)
        for start in range(0, len(input_ids), step):
            end = min(len(input_ids), start + premise_budget)
            char_start = offsets[start][0]
            char_end = offsets[end - 1][1]
            if char_end > char_start:
                windows.append((text[char_start:char_end], char_start, char_end))
            if end == len(input_ids):
                break
        return windows or [(text, 0, len(text))]

    def _candidate_windows(
        self,
        text: str,
        words: Sequence[tuple[int, str]],
    ) -> dict[int, list[str]]:
        matches = list(self._WORD_RE.finditer(text))
        windows = self._premise_windows(text)
        result: dict[int, list[str]] = {}
        for token_index, _ in words:
            if token_index >= len(matches):
                continue
            word_start, word_end = matches[token_index].span()
            matching = [
                window_text
                for window_text, window_start, window_end in windows
                if word_start < window_end and word_end > window_start
            ]
            if not matching:
                matching = [text]
            result[token_index] = matching
        return result

    def score_words(
        self,
        text: str,
        words: Sequence[tuple[int, str]],
        targets: Mapping[Any, str],
    ) -> dict[Any, list[tuple[int, str, float]]]:
        """Return entailment probabilities for every target/word pair."""
        if not words or not targets:
            return {target: [] for target in targets}
        model, tokenizer, device, max_length, entailment_index = self._require_loaded()
        import torch

        candidate_windows = self._candidate_windows(text, words)
        pairs: list[tuple[Any, int, str, str, str]] = []
        for target, hypothesis_template in targets.items():
            for token_index, word in words:
                for premise in candidate_windows.get(token_index, []):
                    hypothesis = hypothesis_template.replace("{word}", word)
                    pairs.append((target, token_index, word, premise, hypothesis))
        if not pairs:
            return {target: [] for target in targets}

        results: dict[Any, dict[int, tuple[str, float]]] = {target: {} for target in targets}
        batch_size = 32
        for start in range(0, len(pairs), batch_size):
            batch = pairs[start:start + batch_size]
            encoded = tokenizer(
                [item[3] for item in batch],
                [item[4] for item in batch],
                return_tensors="pt",
                padding=True,
                truncation="longest_first",
                max_length=max_length,
            )
            model_inputs = {
                key: value.to(device)
                for key, value in encoded.items()
                if key in {"input_ids", "attention_mask", "token_type_ids"}
            }
            with torch.no_grad():
                logits = model(**model_inputs).logits
                probabilities = torch.softmax(logits, dim=-1)[:, entailment_index]
            for item, probability in zip(batch, probabilities.detach().cpu().tolist()):
                target, token_index, word = item[:3]
                previous = results[target].get(token_index)
                if previous is None or probability > previous[1]:
                    results[target][token_index] = (word, float(probability))

        return {
            target: [
                (token_index, word, score)
                for token_index, (word, score) in candidates.items()
            ]
            for target, candidates in results.items()
        }
